// The exposé scanner: run Merit across a list of real MCP servers (scripts/servers.json,
// produced by fetch-registry.mjs) and emit a ranked leaderboard + headline stats.
//
// SAFETY: this installs + launches third-party servers, so run it ONLY in a disposable
// sandbox (the GitHub Actions `expose` workflow). It is static-only by default — it NEVER
// sends live probe payloads, and conformance (which calls one tool per server) is opt-in.
// Not part of the npm package (scripts/ is never published). Usage:
//   node scripts/fetch-registry.mjs --limit=100 && node scripts/expose.mjs [--conformance]
import { run } from "../dist/src/orchestrator.js";
import { readFileSync, writeFileSync } from "node:fs";

const servers = JSON.parse(readFileSync(new URL("./servers.json", import.meta.url), "utf8"));
// Opt-in: conformance CALLS tools (tools-call-simple-text), which can have real side
// effects on powerful third-party servers (browser nav, command exec). Off by default.
const withConformance = process.argv.includes("--conformance");
const PER_SERVER_TIMEOUT = 240000;

function withTimeout(promise, ms) {
  let t;
  const timeout = new Promise((_, rej) => {
    t = setTimeout(() => rej(new Error(`timed out after ${Math.round(ms / 1000)}s`)), ms);
  });
  return Promise.race([promise, timeout]).finally(() => clearTimeout(t));
}

const results = [];
for (const s of servers) {
  process.stderr.write(`▶ scanning ${s.name} …\n`);
  const t0 = Date.now();
  try {
    const report = await withTimeout(
      run({
        connect: { transport: "stdio", command: s.command, env: s.env },
        testsPath: undefined, // no functional tests for third-party servers
        snapshotPath: undefined,
        security: true,
        probe: false, // NEVER send live canary payloads to third-party servers — they have side effects
        conformance: withConformance,
      }),
      PER_SERVER_TIMEOUT,
    );
    const sev = { critical: 0, high: 0, medium: 0, low: 0 };
    for (const f of report.security.findings) sev[f.severity]++;
    results.push({
      name: s.name,
      ok: true,
      verdict: report.verdict,
      score: report.score,
      capped: report.capped,
      security: sev,
      findings: report.security.findings.map((f) => ({ rule: f.ruleId, owasp: f.owasp, sev: f.severity, conf: f.confidence, msg: f.message })),
      conformance: report.conformance.ran ? { passed: report.conformance.passed, total: report.conformance.total } : null,
      ms: Date.now() - t0,
    });
    process.stderr.write(`  ${report.verdict} · ${report.score}/100\n`);
  } catch (e) {
    results.push({ name: s.name, ok: false, error: String(e?.message ?? e) });
    process.stderr.write(`  ✖ could not scan: ${e?.message ?? e}\n`);
  }
}

const scanned = results.filter((r) => r.ok);
const failed = scanned.filter((r) => r.verdict === "FAIL");
const withHigh = scanned.filter((r) => r.security.critical + r.security.high > 0);
const avg = scanned.length ? Math.round(scanned.reduce((a, r) => a + r.score, 0) / scanned.length) : 0;
const pct = (n, d) => (d ? `${Math.round((100 * n) / d)}%` : "0%");

writeFileSync("expose-results.json", JSON.stringify({ generatedAt: new Date().toISOString(), results }, null, 2));

let md = `# The MCP Server Trust Report\n\n`;
md += `_Scanned ${scanned.length} MCP server(s) with [Merit](https://github.com/MeritMCP/meritmcp) on ${new Date().toISOString().slice(0, 10)}._\n\n`;
md += `## Headline\n`;
md += `- **${pct(failed.length, scanned.length)}** of scanned servers **FAIL** the quality gate.\n`;
md += `- **${pct(withHigh.length, scanned.length)}** ship a **high-confidence Critical/High security finding**.\n`;
md += `- Average safety score: **${avg}/100**.\n\n`;
md += `## Leaderboard (worst first)\n\n`;
md += `| Server | Verdict | Score | Crit | High | Med | Conformance |\n|---|---|---|---|---|---|---|\n`;
for (const r of [...scanned].sort((a, b) => a.score - b.score)) {
  const c = r.conformance ? `${r.conformance.passed}/${r.conformance.total}` : "—";
  md += `| \`${r.name}\` | ${r.verdict === "PASS" ? "✅ PASS" : "❌ FAIL"} | ${r.score} | ${r.security.critical} | ${r.security.high} | ${r.security.medium} | ${c} |\n`;
}
const errored = results.filter((r) => !r.ok);
if (errored.length) {
  md += `\n## Could not scan\n`;
  for (const r of errored) md += `- \`${r.name}\` — ${r.error}\n`;
}
md += `\n<sub>Generated by Merit — the CI quality gate for MCP servers. https://github.com/MeritMCP/meritmcp</sub>\n`;
writeFileSync("LEADERBOARD.md", md);
console.log("\n" + md);
